---
- name: RSYNC | Sincronizando diretórios de Rundeck01
  synchronize:
    set_remote_user: yes
    mode: pull
    src: "root@{{ RUNDECK1_HOST }}:{{ item.source }}"
    dest: /tmp/backup-rundeck-{{ backup_date.stdout }}/{{ item.dest }}
  loop:
    - {source: "{{ DIRECTORIES.logs }}", dest: "logs"}
    - {source: "{{ DIRECTORIES.ansible }}", dest: "ansible"}
    - {source: "{{ DIRECTORIES.rundeck }}", dest: "rundeck"}


- name: RSYNC | Verificando diretórios em Rundeck02
  file:
    path: "{{ DIRECTORIES }}"
    state: directory
    recurse: yes
  delegate_to: "{{ RUNDECK2_HOST }}"


- name: RSYNC | Sincronizando arquivos locais para Rundeck02
  synchronize:
    set_remote_user: yes
    src: /tmp/backup-rundeck-{{ backup_date.stdout }}/{{ item.source }}
    dest: "root@{{ RUNDECK2_HOST }}:{{ item.dest }}"
    delete: yes
  loop:
    - {source: "logs/", dest: "{{ DIRECTORIES.logs }}"}
    - {source: "ansible/", dest: "{{ DIRECTORIES.ansible }}"}
    - {source: "rundeck/", dest: "{{ DIRECTORIES.rundeck }}"}