- name: DATE
  command: date '+%d-%m-%Y-%Hh%Mm%Ss'
  register: backup_date
  when: backup_date is not defined

- name: SETUPFOLDER | Criando pasta raiz
  file:
    path: "{{ BACKUP_PATH }}/backup-rundeck-{{ backup_date.stdout }}/{{ item }}"
    state: directory
    recurse: yes
  loop:
    - logs
    - ansible
    - rundeck